site_name: {{ cookiecutter.project_name }} Documentation
site_author: {{ cookiecutter.author_name }}
use_directory_urls: true
# google_analytics: []

# Copyright
copyright: Copyright &copy; 2024 {{ cookiecutter.project_name }}&trade;

repo_url: https://bitbucket.org/
repo_name: Bitbucket

# Configuration
theme:
    name: "material"
    palette:
        scheme: default
        primary: custom
        accent: custom
    icon:
        repo: fontawesome/brands/git-alt
    # logo: img/x_x_white.svg
    favicon: img/favicon.ico
    font:
        text: Ubuntu
        code: Roboto Mono
        # text: Raleway
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.tabs.sticky
        - navigation.top
        # - navigation.footer
        # - navigation.tracking
        # - toc.integrate
        - content.code.copy
        - content.code.annotate


# Extensions
markdown_extensions:
    - abbr
    - attr_list
    - tables
    - admonition
    - sane_lists
    - smarty
    - meta
    - toc:
          toc_depth: 2
          permalink: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.details
    - pymdownx.highlight:
          use_pygments: true
          linenums: false
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
          preserve_tabs: true
          custom_fences:
            # Mermaid diagrams
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tilde
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
    - search
    - awesome-pages
    - minify:
          minify_html: true
          minify_js: true
          minify_css: true
          cache_safe: true

# Customization
extra_css:
    - css/extra.css

# extra_javascript:
    # - js/extra.js

nav:
    - Getting Started:
        - index.md

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/username
        - icon: fontawesome/brands/facebook
          link: https://facebook.com/username
        - icon: fontawesome/brands/instagram
          link: https://instagram.com/username
